version: "3.9"

services:
  web:
    build: .
    container_name: emergency_web
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn emergency_news.wsgi:application --bind 0.0.0.0:8000
      "
    environment:
      DJANGO_SETTINGS_MODULE: emergency_news.settings
      SECRET_KEY: supersecretkey123
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgresql://emergency_user:chiadetech@db:5432/emergency_news_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    container_name: emergency_worker
    command: celery -A emergency_news worker -l info
    environment:
      DJANGO_SETTINGS_MODULE: emergency_news.settings
      DATABASE_URL: postgresql://emergency_user:chiadetech@db:5432/emergency_news_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  beat:
    build: .
    container_name: emergency_beat
    command: celery -A emergency_news beat -l info
    environment:
      DJANGO_SETTINGS_MODULE: emergency_news.settings
      DATABASE_URL: postgresql://emergency_user:chiadetech@db:5432/emergency_news_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      worker:
        condition: service_started

  db:
    image: postgres:15
    container_name: emergency_db
    restart: always
    environment:
      POSTGRES_DB: emergency_news_db
      POSTGRES_USER: emergency_user
      POSTGRES_PASSWORD: chiadetech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emergency_user -d emergency_news_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: emergency_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
